### ISSUE TITLE
Fast-forward branch merging doesn't update local tree viewer

### ISSUE THREAD

**Issue by shangdrk** [dmusican/Elegit#154]
In my case, I had `master` and another branch called `new_branch`. Merging `new_branch` into `master` is fast-forward, but after I merged them, the local tree viewer didn't change:
![image](https://cloud.githubusercontent.com/assets/7304910/14697829/45b0c5d0-074d-11e6-9dc4-e6629dc1bb0b.png)

I closed the program and reopened it, which fixed the problem (the following is a screenshot of what it looks like after reopening):
![image](https://cloud.githubusercontent.com/assets/7304910/14697839/783e4658-074d-11e6-921d-48e446c21a3d.png)

We probably want the change to be reflected on UI right after merging.

**Comment by shangdrk** [comment]
What's worse, after the merge, `master` is changed so there should be a new commit automatically created in `master`. But in Elegit there's no sign of the new commit, and pressing push doesn't do anything, because Elegit thinks there's no new commit.

At the same time, if you use command line and type `git status`, here's what I got:

> On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

Apparently it's contradictory to what Elegit says.

**Comment by kileymaki** [comment]
I think this is an issue with the labels updating in general, not just in this specific case. I will look more into it. As for your update, I was unable to reproduce that. After merging the fast forward, I was able to push as expected and Elegit correctly updated.

**Comment by dmusican** [comment]
Derek: try to reproduce, and fork repo!

Kiley: kill off branchesAsHead, and try to verify that the labels are not dependent on them

Clean up tool-tip string scraping code, change to presumably a nice comfy method call that both tooltip and this technique use? Once you've decided the structure of that method, first write a unit test!!!!! :):):)

**Comment by shangdrk** [comment]
**How to reproduce the bug**
1. Clone [this repo](url) into two local repos (say, repo1, repo2)
2. In repo1, create a new branch new_branch. Checkout that branch, and then change readme.txt. Save the file.
3. In elegit, commit changes and push new_branch.
4. Switch to repo2, fetch changes and track new_branch.
5. Merge new_branch into master.

After these steps, elegit won't show you there's a new commit in repo2 after merge, but command line "git status" will tell you there is a new commit.

**Comment by dmusican** [comment]
Confirm?

**Comment by erictwalker18** [comment]
This is a nasty one... I tested it on https://github.com/erictwalker18/testRepo1 (the link above doesn't work), and Elegit does show the new commit in repo2, however, even with a clean clone, elegit constantly tells me that there are new changes in the repo, even though there aren't.

In terms of a commit turning 'invisible' (dotted out), this happens when you commit changes (and don't push), then switch to a different repo, then come back. This doesn't affect whether or not you can push, it appears to just be a UI problem.

There is a problem with the branch names. If you push something in new_branch in repo1, then fetch/merge in repo2, then commit a change in new_branch in repo2, then go back to repo1, you'll see origin/origin/new_branch as a branch.

**Comment by erictwalker18** [comment]
This bug is fixed, see bugs #166 and #167
