### ISSUE TITLE
Julia's push/pull bug

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#165]
Julia: rename this bug, and enter details here.

Kiley: can you actually fix this? Can you first generate a unit test that breaks?

**Comment by connellyj** [comment]
How to recreate the bug:

This has happened to me with any repo I've used, but here's a fork of one that I know reproduces the bug: https://github.com/connellyj/UG_fork3.git

1) Open Elegit
2) Clone the repo into a local directory named repo1
3) Create a new file Test.txt in repo1 and commit the change
4) Remove repo1 from the Elegit UI
5) Clone the same repo into a local directory named repo2
6) Re-add repo1 to the Elegit UI (load existing repository, don't re-clone it)
7) Push the commit from earlier
8) Switch to repo2 and fetch and merge
9) Switch back to repo1, and the last commit should be sold in both the local and remote cache, but the bug is when they're dotted out
10) Switch back to repo2 and the last commit in the local and remote cache might also be dotted out

**Comment by kileymaki** [comment]
I recreated this with a different repository as well (so I assume it's not repository specific), using the following simplified steps:

1. Have the same repository loaded into two different locations
2. Make a commit in one of them
3. Switch to the second repository
4. Switch back to the repository where the commit was made

This makes the local commit have a dotted line instead of being solid, as expected

**Comment by kileymaki** [comment]
So this is a weird one....

After removing a repository from Elegit and loading a different once, making a commit displays the local tree for the OLD repository. I think this is what's happening with this issue, but I'm not 100% on that.

I've attached an image of the result.
![screen shot 2016-05-24 at 2 02 40 pm](https://cloud.githubusercontent.com/assets/4149841/15516417/62672d38-21b8-11e6-880f-cc2542fadb2e.png)
