### ISSUE TITLE
Elegit hangs occasionally after cloning a repo

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#175]
In the user test that we did on 5/30/16, 3 students experienced Elegit freezing up (spinning beach ball) after cloning a small repo containing one commit and a single file in it. They could work around it by killing Elegit and starting it up again, at which point the repo was already cloned. This has got to be some sort of race condition. The good news is that we know roughly where it is. Can we first duplicate with Thread.sleep / Thread.yield / etc with threads that occur around this particular operation?

This is a tough bug, but I'm labeling it as high priority because it hit 3 users out of 20. It's worth spending time on finding.

**Comment by dmusican** [comment]
For version of Elegit that was used for user test, list here in a comment to this issue, all uses of threads that are encountered in the Worker threads, runLater back on GUI, etc. List here via file and line number.

(Next steps after that, which we will address after absorbing above: try to hang Elegit when cloning a repo by adding combos of Thread.sleep and Thread.yield at operations around a clone. Look at the series of methods called when doing a clone, and observe all usages of threads. Try up to 20 different combinations of these sleep/yields to see if can make something hang. Can make this faster to test by writing a unit test around the clone operation, perhaps.)

**Comment by erictwalker18** [comment]
Threads:
SessionController 350: THREAD: refreshRecentReposInDropdown(), theModel.openRepoFromHelper(). setRecentReposDropdownToCurrentRepo, initPanelViews(), updateUIEnabledStatus(), also shows and hides the busy window around creation of the thread
    SessionController 423: refreshRecentReposInDropdown(): PLATFORM.runlater: sets dropdown to it list of repo helpers from this.theModel.getAllRepoHelpers
    SessionController 992: initPanelViews: synchronized method, shows and hides busy window

Surprisingly no other threads are here, that's why startup takes so long for something as big as Elegit. It should also be noted that the repository monitor is running, so if one hit it right, a gitStatus() will run during the clone. I'm thinking this would be the place to look.

**Comment by dmusican** [comment]
Bug is hiding. Might be dead. Classifying as "can't duplicate" and waiting for next sighting.
