### ISSUE TITLE
Make Elegit handle commits with >2 parents

### ISSUE THREAD

**Issue by connellyj** [dmusican/Elegit#245]

**Comment by erictwalker18** [comment]
No, it should

**Comment by dmusican** [comment]
High priority to make sure Elegit handles this gracefully in some way. Medium priority to do this "right."

**Comment by erictwalker18** [comment]
![image](https://cloud.githubusercontent.com/assets/9425833/16954577/fb4c8750-4d96-11e6-9b04-15aaa690debd.png)
Turns out elegit just doen't draw the last line, but does handle it gracefully. Will work on that. Also interestingly, git doesn't allow 'octopus merge' (merge with >1) commit unless there are no conflicts.
