### ISSUE TITLE
Staging area redesign

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#372]
Should we make a column or a tab in the files panel view for staging area/index?

**Comment by dmusican** [comment]
Fun question: is the index/staging area just those items which have changed, or everything? We just verbally talked about how it was documented somewhere that the index was everything that goes in the commit, including current versions. I remember that. And yes, from the official git documentation on commit (in "git help commit"), in the EXAMPLES section:

"When recording your own work, the contents of modified files in your working tree are temporarily stored to a staging area called the "index" with git add....  Instead of staging files after each individual change, you can tell git commit to notice the changes to the files whose contents are tracked in your working tree and do corresponding git add and git rm for you."

Is the git terminology inconsistent? This would make a great blog posting.
