### ISSUE TITLE
Password dots unreasonably large

### ISSUE THREAD

**Issue by calebbraun** [dmusican/Elegit#514]
Why are the password dots so big?

<img width="457" alt="screen shot 2017-05-25 at 1 43 56 pm" src="https://cloud.githubusercontent.com/assets/12344924/26465303/4cd2811c-4150-11e7-8bee-3ec2c2fb963a.png">

**Comment by ahsanbarkati** [comment]
I am new to open source and I want to solve this issue. Could you please tell me where is the code for this authorize window?

**Comment by calebbraun** [comment]
Welcome to Elegit and thanks for your interest in helping! The code for the window in the screenshot is in the file RepoHelperBuilder.java.

**Comment by ahsanbarkati** [comment]
I will do it. Assign it to me.

**Comment by dmusican** [comment]
Hey @ahsanbarkati : it's yours. Thanks for jumping in to help out! If you don't mind me asking: how did you find Elegit?

To try to get this done, just fork the repo and then send a pull request when you've got a proposed update. Thanks!

**Comment by ahsanbarkati** [comment]
Thanks. I reached here by a google search for git GUI. 
In javaFX the unicode for the echo character is hard-coded in the import file: com.sun.javafx.scene.control.skin.TextFieldSkin.java

![screenshot from 2017-06-07 03-29-18](https://user-images.githubusercontent.com/11457225/26853938-a3ef917a-4b31-11e7-8bf3-46e86f672bf1.png)

This u25cf is the unicode for that black dot. we can change it to medium black dot by using u26ab.
But since it is in import file of jdk. we can only get desired binary even if we change the import file.
Please suggest me something.

**Comment by dmusican** [comment]
@ahsanbarkati, nice find. That's pretty funny that it's hardcoded in. Here's a fix, perhaps:

https://stackoverflow.com/questions/35688835/bullet-to-asterisk-in-a-passwordfield

I'd consider this way low priority, but @ahsanbarkati  -- if you're having fun and want to make that fix, go for it.

**Comment by ahsanbarkati** [comment]
@dmusican, it was just a little effort to make this fix.

**Comment by ahsanbarkati** [comment]
if any more changes are required then please tell me.

**Comment by dmusican** [comment]
Much appreciated, and thank you. Feel free to snag any other bugs you might be interested in fixing.
