### ISSUE TITLE
The cloud and "node" icons on the right side of branch labels are misbehaving

### ISSUE THREAD

**Issue by MarthanielX** [dmusican/Elegit#523]
Every branch is showing up with the node icon besides the current local and remote tracking branches. The labels are meant to show whether branches are local or remote, but is this even necessary considering it always says origin/_____ for remote branches?

**Comment by dmusican** [comment]
Pull request I made didn't quite fix all cases; still working on it.

**Comment by dmusican** [comment]
This is now fixed identically to fix proposed by @calebbraun . There's still a related but separate bug where if the branch name is too long, it doesn't show up as a cloud icon. That's because we do an incorrect comparison between the abbreviated name and the full name. I'm going to fix that imminently. The code is a little messy regarding this; I'll clean up while I'm in there.

**Comment by dmusican** [comment]
Fixed.
