### ISSUE TITLE
Clarify what's going on with commit children highlighting

### ISSUE THREAD

**Issue by grahamearley** [dmusican/Elegit#86]
Perhaps add it to a right-click context menu with a label

**Comment by kileymaki** [comment]
I've refactored how commits are highlighted. There are now a couple options in a right click menu for showing different relationships (including children, parents, all ancestors, and all descendants).

Edges disappearing has been (possibly temporarily, possibly permanently) disabled since it was starting to have a performance impact once we got above 350 commits or so in the test repo.
